### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by muspelheim** [spatie/async#113]
Hi, I stuck with exception handling by this library, 
https://github.com/spatie/async/blob/master/src/Output/SerializableException.php#L28

Sometimes you can get an exception with different amount of constructor parameters and this class will not be handled correctly, for example, https://github.com/doctrine/dbal/blob/2.10.x/lib/Doctrine/DBAL/Exception/DriverException.php#L26

Can you please suggest how we can solve this problem?

**Comment by brendt** [comment]
Feel free to submit a PR with a proposed solution or a failing test.

**Comment by klaude** [comment]
I've run into a similar case where the `SerializableException` can't handle [Guzzle exceptions](https://github.com/guzzle/guzzle/blob/master/src/Exception/BadResponseException.php) for similar reasons. 

It looks like the serializable exception assumes the underlying exception's constructor follows PHP's exception constructor signature. The only way I can think of to get around this is to bypass the `SerializableException` and use the underlying exception directly in [`ChildRuntime.php`](https://github.com/spatie/async/blob/master/src/Runtime/ChildRuntime.php), serializing it with a custom serializer that can filter out non-serializable items in the exception instead of using PHP's `serialize()` which fatals out. Something like:

```
} catch (Throwable $exception) {
    fwrite(STDERR, base64_encode(customSerialize($exception)));
    exit(1);
}
```

How's this sound?

**Comment by brendt** [comment]
That won't work, you can't serialize exceptions.

**Comment by brendt** [comment]
Merged: https://github.com/spatie/async/pull/119
