### ISSUE TITLE
Can I use it in PHP-FPM？

### ISSUE THREAD

**Issue by hkui** [spatie/async#139]

**Comment by spacemudd** [comment]
You need the CLI to run it (so, either you use Queue manager or use something like Artisan CLI commands)

**Comment by DoobleD** [comment]
Hi @spacemudd. Any chance you could elaborate on that? I'm interested in using `spatie/async` with `php-fpm` as well, but not sure how to do that since pcntl is disabled for` php-fpm`.

**Comment by spacemudd** [comment]
Hi @DoobleD. You need to enable pcntl. I've been using Laravel Queue Manager that runs php processes in the background where spatie/async works. However, its performance was great for small pure php scripts. I've since changed back to regular queues (Laravel queues, or something like RabbitMQ for other apps)

**Comment by DoobleD** [comment]
Thanks for the insight @spacemudd. I've ended up creating and starting multiple Symfony processes from fpm, each one running a Symfony command script. Probably not the best solution, but does the job relatively easily.
