### ISSUE TITLE
Database connection can not be resolved

### ISSUE THREAD

**Issue by innobrig** [spatie/async#49]
I'm testing your package to see if it makes sense for us to use async DB inserts in order to improve performance and I'm running into the following problem when calling $dbModelObject->save() (I should mention that we're using Eloquent and specifically the mongodb extension for it (jenssegers/mongodb) but I'm suspecting that this is generic issue): 

    PHP Fatal error:  Uncaught Error: Call to a member function connection() on null
    #0 /var/www/html/BoostFixes/vendor/illuminate/database/Eloquent/Model.php(1205): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
    #1 /var/www/html/BoostFixes/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(412): Illuminate\Database\Eloquent\Model->getConnection()
    #2 /var/www/html/BoostFixes/vendor/illuminate/database/Eloquent/Model.php(950): Jenssegers\Mongodb\Eloquent\Model->newBaseQueryBuilder()
    #3 /var/www/html/BoostFixes/vendor/illuminate/database/Eloquent/Model.php(628): Illuminate\Database\Eloquent\Model->newModelQuery()
    #4 /var/www/html/BoostFixes/src/Model/BaseModel.php(395): Illuminate\Database\Eloquent\Model->save()
    #5 closure://function() use ($bet) { $bet->save (); }(2): Boost\Model\BaseModel->save()
    #6 /var/www/html/BoostFixes/vendor/spatie/async/src/Runtime/ChildRuntime.php(25): Opis\Closure\SerializableClosure->{closure}()
    #7 {main} in /var/www/html/BoostFixes/vendor/spatie/async/src/Output/Serializab in /var/www/html/BoostFixes/vendor/spatie/async/src/Output/SerializableException.php on line 28

Just to be clear, the code works fine without using your package; it seems to be that somehow the DB context is  not available in the child/async process. Could you please advise how/if it is possible to get this to work?

**Comment by brendt** [comment]
Hi @innobrig 

It's important to know that child processes will not bootstrap the whole Laravel framework, this would be way too much overhead. This is where tasks can be used in order to "prepare the child process". Take a look at the README over here: https://github.com/spatie/async#working-with-tasks

If you're bootstrapping Laravel in every child process; you'll have to take into account that this will introduce some overhead. It would make sense to bundle several tasks into one, to outbalance this overhead.

Say you're capping the amount of child processes to 10, and have maybe 5000 queries to execute. I'd bundle these 5000 queries into chunks of maybe 100 or 200, and pass these queries to a task.

Also remember that it'll be important to run the queries itself asynchronously. It wouldn't make any difference if you're using 10 processes, if you database server can only serve one request at once. (I don't know if this is default in mongoDB or not).

Hope this helps! Feel free to share your findings.

**Comment by innobrig** [comment]
Thank you very much for the info you provided, I think you pointed me in the right direction. I'll experiment with this ...

**Comment by pesseyjulien** [comment]
hi @brendt ,

Sorry to dig up this issue but you mentioned "bootstrapping Laravel in every child process", I'm trying to do this with Symfony in a task class but don't really know how.

Do you have an example by any chance ?

**Comment by brendt** [comment]
In Laravel's case it's by requiring `bootstrap.php`, I suppose Symfony has something similar?

**Comment by pesseyjulien** [comment]
Yep found the solution : 

```
        if ($this->env['APP_DEBUG'] === '1') {
            umask(0000);
            Debug::enable();
            DebugClassLoader::disable();
        }

        $kernel = new \AppKernel($this->env['APP_ENV'], (bool) $this->env['APP_DEBUG']);
        $kernel->boot();

        return $kernel->getContainer();
```

Not as easy as Laravel but working :)

**Comment by valh1996** [comment]
Hello @pesseyjulien do you have a full working example maybe please ? I'm having some difficulties with this...s :)

**Comment by pesseyjulien** [comment]
Sure, check this out : https://github.com/amphp/parallel/issues/115#issuecomment-631442739

**Comment by valh1996** [comment]
Thank you very much, I'll look into it :). 

On the other hand, some classes seem to be specific to AMP, is this example compatible with `Spatie/Async`? I'd rather have Laravel instead of Symfony.

**Comment by pesseyjulien** [comment]
I guess you can apply the same logic while using Spatie yes. 

Cannot help you with Laravel, sorry !
