### ISSUE TITLE
The serialized output may only be 10240 bytes long. - Is there a reason for this limit?

### ISSUE THREAD

**Issue by modstore** [spatie/async#76]
I want to get html responses from my callback, but this limit isn't allowing me to. Just wondering if there's a reason for this limit? Could be be something that's overridable?

```php
$pool[] = async(function () use ($url) {
    $response = parent::request('GET', $url);

    // ...

    return $response->getBody()->getContents();
})->then(function ($response) use ($pool) {
    // ...
});
```

This limit is set in vendor/spatie/async/src/Runtime/ChildRuntime.php:29
$outputLength = 1024 * 10;

**Comment by modstore** [comment]
Just following up on this, I decided to go another path to solve my problem, so this doesn't really matter for me any more.

**Comment by yongkylie** [comment]
@modstore I am also facing this problem. Can you please re-open this issue? At the moment, I changed the formula to $outputLength = 1024 * 100;. I don't know where this would affect, but by changing the value the code works perfectly.

**Comment by brendt** [comment]
Feel free to submit a tested PR to make in configurable

**Comment by yongkylie** [comment]
@brendt what's the purpose of the `outputLength` limit?

**Comment by brendt** [comment]
Outputs that are too large will crash the process. `1024 * 10` can probably be increased, though I suppose the exact amount depends on the system.

You can make this configurable if we'd add support for it:

- The output length should be configured in `\Spatie\Async\Runtime\ParentRuntime`
- This config value should be passed to the child runtime here: `https://github.com/spatie/async/blob/master/src/Runtime/ParentRuntime.php#L70`
- It should be read in the child runtime here: https://github.com/spatie/async/blob/master/src/Runtime/ChildRuntime.php#L7

We could make `outputLength` nullable, so that you could also disable it altogether.

I want to emphasize that passing these large amounts of data between the parent and child processes probably means you're using this library wrong. The idea is to offload time-consuming IO tasks as separate processes and execute them in parallel. If you need complex communication from the child process to the parent process, you're better off storing results in eg. a database and reading it from the parent process, after the child was finished.

**Comment by techno-express** [comment]
> I want to emphasize that passing these large amounts of data between the parent and child processes probably means you're using this library wrong.

You should show an actually example of that for proof. What are you referencing to make that claim? This is an excellent project that I see self imposed restrictions applied. 

My [fork](https://github.com/techno-express/async) has windows os support. I have also portioned it off to be just an symfony process wrapper https://github.com/symplely/processor, it does address that issue in https://github.com/spatie/async/issues/75.

The Symfony project has requests for an wrapper like interface: https://github.com/symfony/symfony/pull/23596, https://github.com/symfony/symfony/issues/8454.

**Comment by brendt** [comment]
It's configurable as of 1.1.0: https://github.com/spatie/async/releases/tag/1.1.0 (#86)
